// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterApp.DataAccess.EntitiyFrameworkCore;

#nullable disable

namespace ShelterApp.DataAccess.Migrations
{
    [DbContext(typeof(ShelterAppDbContext))]
    [Migration("20240407180440_PropertiesChanged")]
    partial class PropertiesChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShelterApp.Entities.Entities.Blog.TBL_Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("DateTime");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVarChar");

                    b.HasKey("ID");

                    b.ToTable("TBL_Blog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
